server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: graphql
          uri: http://localhost:8080/graphql
          predicates:
            - Path=/library
          filters:
            - RewritePath=/library, /graphql
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  redis:
    host: localhost
    port: 6379
  security:
    user: # Only for a quick starter of this project - do not use in any environment
      name: alice
      password: test

wavefront:
  application:
    name: graphql-library
    service: edge-gateway
