server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: graphql
          uri: http://localhost:8080/graphql
          predicates:
            - Path=/library
          filters:
            - RewritePath=/library, /graphql


wavefront:
  application:
    name: graphql-library
    service: edge-gateway
